In [ ]:
pip install scikit-learn==1.1.3

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.5/30.5 MB 39.6 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 0.15.0 requires scikit-learn>=1.2.2, but you have scikit-learn 1.1.3 which is incompatible.


In [ ]:
from sklearn.datasets import load_boston
X,y = load_boston(return_X_y =True)


/usr/local/lib/python3.10/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [ ]:
X[0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [ ]:
X.shape

(506, 13)

In [ ]:
y.shape

(506,)

In [ ]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
help(Sequential)

In [ ]:
# initilized the model
model = Sequential()
model.add(Dense(12,input_dim=X.shape[1],activation = "relu")) # input layer
model.add(Dense(12,activation="relu")) # Hidden Layer
model.add(Dense(1,activation="linear")) # output layer

In [ ]:
# compile the model
model.compile(loss="mean_squared_error", optimizer="adam", metrics=["mean_absolute_percentage_error"]) # optimizwer


In [ ]:
model.fit(X,y, epochs= 2500, batch_size=100)

Streaming output truncated to the last 5000 lines.
6/6 [==============================] - 1s 5ms/step - loss: 17466.7578 - mean_absolute_percentage_error: 658.0280
Epoch 2/2500
6/6 [==============================] - 0s 4ms/step - loss: 9339.9219 - mean_absolute_percentage_error: 458.4706
Epoch 3/2500
6/6 [==============================] - 0s 3ms/step - loss: 4426.1328 - mean_absolute_percentage_error: 285.1845
Epoch 4/2500
6/6 [==============================] - 0s 3ms/step - loss: 1976.0488 - mean_absolute_percentage_error: 158.3134
Epoch 5/2500
6/6 [==============================] - 0s 3ms/step - loss: 1089.8564 - mean_absolute_percentage_error: 134.8764
Epoch 6/2500
6/6 [==============================] - 0s 3ms/step - loss: 930.8800 - mean_absolute_percentage_error: 145.4736
Epoch 7/2500
6/6 [==============================] - 0s 3ms/step - loss: 969.8040 - mean_absolute_percentage_error: 152.8171
Epoch 8/2500
6/6 [==============================] - 0s 3ms/step - loss: 921.4202 - mean_

In [ ]:
accuracy = model.evaluate(X,y)

16/16 [==============================] - 0s 2ms/step - loss: 20.0896 - mean_absolute_percentage_error: 16.9526


In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 12)                168       
                                                                 
 dense_1 (Dense)             (None, 12)                156       
                                                                 
 dense_2 (Dense)             (None, 1)                 13        
                                                                 
Total params: 337 (1.32 KB)
Trainable params: 337 (1.32 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# Classification

In [ ]:
from sklearn.datasets import load_breast_cancer
X, y = load_breast_cancer(return_X_y=True)

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
X[0]

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(15,input_dim =X.shape[1], activation = "relu"))
model.add(Dense(15, activation="relu"))
model.add(Dense(1, activation= "sigmoid"))

In [ ]:
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
model.fit(X,y, epochs= 150, batch_size=10)

Epoch 1/150
57/57 [==============================] - 1s 2ms/step - loss: 3.8143 - accuracy: 0.8032
Epoch 2/150
57/57 [==============================] - 0s 2ms/step - loss: 0.8431 - accuracy: 0.8805
Epoch 3/150
57/57 [==============================] - 0s 2ms/step - loss: 0.7435 - accuracy: 0.9016
Epoch 4/150
57/57 [==============================] - 0s 2ms/step - loss: 0.6162 - accuracy: 0.9121
Epoch 5/150
57/57 [==============================] - 0s 2ms/step - loss: 0.5934 - accuracy: 0.9069
Epoch 6/150
57/57 [==============================] - 0s 2ms/step - loss: 0.5134 - accuracy: 0.9209
Epoch 7/150
57/57 [==============================] - 0s 2ms/step - loss: 0.5679 - accuracy: 0.8981
Epoch 8/150
57/57 [==============================] - 0s 2ms/step - loss: 0.4759 - accuracy: 0.9086
Epoch 9/150
57/57 [==============================] - 0s 2ms/step - loss: 0.4159 - accuracy: 0.9104
Epoch 10/150
57/57 [==============================] - 0s 2ms/step - loss: 0.4788 - accuracy: 0.9051
Epoch 11/

In [ ]:
accuracy = model.evaluate(X,y)

18/18 [==============================] - 0s 2ms/step - loss: 0.1791 - accuracy: 0.9192


In [ ]:
y.shape

(569,)

In [ ]:
x_pred = model.predict(X)

18/18 [==============================] - 0s 2ms/step


In [ ]:
x_pred

array([[2.76146348e-18],
       [8.80318214e-12],
       [4.08231848e-09],
       [3.52017917e-02],
       [1.78969719e-06],
       [3.57156084e-03],
       [7.12474635e-10],
       [2.99235515e-04],
       [8.67672823e-03],
       [7.12895999e-05],
       [2.48840824e-05],
       [1.29499460e-08],
       [9.44745989e-05],
       [1.62910178e-01],
       [4.29830045e-01],
       [1.07625179e-04],
       [2.59208917e-07],
       [7.22913951e-09],
       [2.72481139e-23],
       [8.75918865e-01],
       [9.73137319e-01],
       [9.99907911e-01],
       [7.25065544e-03],
       [1.26705705e-25],
       [2.00868715e-26],
       [2.62100528e-08],
       [2.53406982e-03],
       [3.42336284e-06],
       [1.54900337e-09],
       [1.57544529e-03],
       [1.00480915e-10],
       [2.32060373e-07],
       [8.63592788e-08],
       [6.00482609e-13],
       [1.45896706e-07],
       [1.31773668e-05],
       [2.23065495e-01],
       [9.99886930e-01],
       [4.29573134e-02],
       [1.35893792e-01],


In [ ]:
import numpy as np
predict_x = model.predict(X)
classes_x = np.argmax(predict_x, axis = 1)

18/18 [==============================] - 0s 2ms/step


In [ ]:
predict_x

array([[2.76146348e-18],
       [8.80318214e-12],
       [4.08231848e-09],
       [3.52017917e-02],
       [1.78969719e-06],
       [3.57156084e-03],
       [7.12474635e-10],
       [2.99235515e-04],
       [8.67672823e-03],
       [7.12895999e-05],
       [2.48840824e-05],
       [1.29499460e-08],
       [9.44745989e-05],
       [1.62910178e-01],
       [4.29830045e-01],
       [1.07625179e-04],
       [2.59208917e-07],
       [7.22913951e-09],
       [2.72481139e-23],
       [8.75918865e-01],
       [9.73137319e-01],
       [9.99907911e-01],
       [7.25065544e-03],
       [1.26705705e-25],
       [2.00868715e-26],
       [2.62100528e-08],
       [2.53406982e-03],
       [3.42336284e-06],
       [1.54900337e-09],
       [1.57544529e-03],
       [1.00480915e-10],
       [2.32060373e-07],
       [8.63592788e-08],
       [6.00482609e-13],
       [1.45896706e-07],
       [1.31773668e-05],
       [2.23065495e-01],
       [9.99886930e-01],
       [4.29573134e-02],
       [1.35893792e-01],


In [ ]:
classes_x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
import numpy as np
Xnew = np.array([[0.89337759, 0.65864154]])
ynew = model.predict(Xnew)

InvalidArgumentError: ignored

In [ ]:
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)

In [ ]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
model = Sequential()
model.add(Dense(15,input_dim=X.shape[1],activation="relu"))
model.add(Dense(15,activation ="relu"))
model.add(Dense(3,activation = "softmax"))


In [ ]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
model.fit(X,y, epochs= 150, batch_size=10)

Epoch 1/150
15/15 [==============================] - 1s 2ms/step - loss: 1.4959 - accuracy: 0.3333
Epoch 2/150
15/15 [==============================] - 0s 2ms/step - loss: 1.1978 - accuracy: 0.3333
Epoch 3/150
15/15 [==============================] - 0s 2ms/step - loss: 1.1205 - accuracy: 0.2333
Epoch 4/150
15/15 [==============================] - 0s 2ms/step - loss: 1.0670 - accuracy: 0.1467
Epoch 5/150
15/15 [==============================] - 0s 2ms/step - loss: 1.0157 - accuracy: 0.3400
Epoch 6/150
15/15 [==============================] - 0s 2ms/step - loss: 0.9732 - accuracy: 0.5667
Epoch 7/150
15/15 [==============================] - 0s 2ms/step - loss: 0.9333 - accuracy: 0.6667
Epoch 8/150
15/15 [==============================] - 0s 2ms/step - loss: 0.8895 - accuracy: 0.6667
Epoch 9/150
15/15 [==============================] - 0s 2ms/step - loss: 0.8403 - accuracy: 0.6667
Epoch 10/150
15/15 [==============================] - 0s 2ms/step - loss: 0.7952 - accuracy: 0.7467
Epoch 11/