In [ ]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN

In [ ]:
model = Sequential()
model.add(SimpleRNN(3,input_shape=(4,5)))
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 3)                 27        
                                                                 
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 31 (124.00 Byte)
Trainable params: 31 (124.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
print(model.get_weights()[0].shape)
model.get_weights()[0]

(5, 3)


array([[-0.03935218, -0.0617367 ,  0.32472318],
       [-0.85134596, -0.3215614 , -0.46414483],
       [ 0.50512975, -0.6195277 ,  0.26573366],
       [ 0.16389447, -0.25957775, -0.68467724],
       [-0.4345658 , -0.03788185,  0.308204  ]], dtype=float32)

In [ ]:
print(model.get_weights()[1].shape)
model.get_weights()[1]

(3, 3)


array([[-0.8669199 ,  0.18301286,  0.46363363],
       [ 0.18746775, -0.74214625,  0.6434862 ],
       [ 0.46185032,  0.64476734,  0.6090725 ]], dtype=float32)

RNN integer Encoding Technique
Embedding Techning

In [ ]:
# RNN integer Encoding Technique
import numpy as np

docs = ['go india',
        'india india',
        'hip hip hurray',
        'jeetega bhai jeetega india jeetega',
        'bharat mata ki jai',
        'kohli kohli',
        'sachin sachin',
        'dhoni dhoni',
        'modi ji ki jai',
        'inquilab zindabad']


In [ ]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<Nothing>') #out of vocab token


In [ ]:
tokenizer.fit_on_texts(docs)

In [ ]:
tokenizer.word_index

{'<Nothing>': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'zindabad': 18}

In [ ]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('zindabad', 1)])

In [ ]:
tokenizer.document_count

10

In [ ]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [ ]:
from keras.utils import pad_sequences

In [ ]:
sequences = pad_sequences(sequences, padding='post')

In [ ]:
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

integer encoding simplernn imdb project

In [ ]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [ ]:
(X_train, y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 [==============================] - 1s 0us/step


In [ ]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [ ]:
X_train.shape,y_train.shape,X_test.shape,y_test.shape

((25000,), (25000,), (25000,), (25000,))

In [ ]:
len(X_train[0])

218

In [ ]:
X_train = pad_sequences(X_train,padding='post',maxlen=200)
X_test = pad_sequences(X_test,padding='post',maxlen=200)

In [ ]:
len(X_train[0])

200

In [ ]:
X_train.shape

(25000, 200)

In [ ]:
model = Sequential()

model.add(SimpleRNN(32, input_shape=(200,1),return_sequences=False, activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 38s 47ms/step - loss: 22.0291 - accuracy: 0.4961 - val_loss: 8.6915 - val_accuracy: 0.4939
Epoch 2/5
782/782 [==============================] - 36s 46ms/step - loss: 8.4830 - accuracy: 0.5014 - val_loss: 5.0874 - val_accuracy: 0.4988
Epoch 3/5
782/782 [==============================] - 39s 50ms/step - loss: 6.2730 - accuracy: 0.4988 - val_loss: 4.8689 - val_accuracy: 0.4982
Epoch 4/5
782/782 [==============================] - 38s 49ms/step - loss: 6.1237 - accuracy: 0.5009 - val_loss: 3.2422 - val_accuracy: 0.4942
Epoch 5/5
782/782 [==============================] - 38s 49ms/step - loss: 5.1504 - accuracy: 0.5006 - val_loss: 2.5566 - val_accuracy: 0.5060


Embedding

In [ ]:
model = Sequential()
model.add(Embedding(17,output_dim=2, input_length=5))

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 5, 2)              34        
                                                                 
Total params: 34 (136.00 Byte)
Trainable params: 34 (136.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile('adam','accuracy')

In [ ]:
pred = model.predict(sequences)
print(pred)

ValueError: ignored